#!/bin/bash

# Specify the file name and location
file_name="git_12/hi.txt"

# Create the directory if it doesn't exist
mkdir -p "$(dirname "$file_name")"

# Write the YAML content to the file
cat <<EOF >"$file_name"
name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run shell script
        run: |
          # Add your shell script commands here
          echo "Hello, world!"
          # You can also reference a shell script file using "./path/to/script.sh"

EOF

echo "File created successfully at: $file_name"
