name: my workflow
on: push

jobs:
  name-of-job:
    runs-on: ubuntu-latest

    steps:
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: git_12/y.html

    
          
                 
         
    
