name: my workflow
on: push

jobs:
  name-of-job:
    runs-on: ubuntu-latest
  
    steps:
      - run: | 
              pwd 
              ls -alh
               git clone https://github.com/jollyjester-1/git_12.git
                cd ${GITHUB_WORKSPACE}
                ls -alh
                 
         
    
