name: my workflow
on: push

jobs:
  name-of-job:
    runs-on: ubuntu-latest
  
    steps:
      - run: pwd 
      - run: ls -alh
      - run: git clone git@github.com:jollyjester-1/git_12.git
      - run: ls -alh
         
    
