name: my workflow
on: push

jobs:
  name-of-job:
    runs-on: ubuntu-latest
  
    steps:
      - run: |
         pwd 
         sudo rm -R y.html
         git add .
         git commit -m "hi"
         git push origin master
    
