name: my workflow
on: push

jobs:
  name-of-job:
    runs-on: ubuntu-latest
  
    steps:
      - run: | 
              pwd 
              ls -alh
              cd ${GITHUB_WORKSPACE}
              pwd
                 
         
    
